module.exports = [{
    "tag": "玄幻小说",
    "tag_url": "https://www.biquge.com.cn/xuanhuan/",
    "source": "笔趣阁",
    "aid": 26583,
    "title": "灭世武修",
    "href": "https://www.biquge.com.cn/book/26583/",
    "author": "天上无鱼",
    "lastUpdate": 1576368000,
    "status": 1
}, {
    "tag": "玄幻小说",
    "tag_url": "https://www.biquge.com.cn/xuanhuan/",
    "source": "笔趣阁",
    "aid": 14745,
    "title": "异界海盗王",
    "href": "https://www.biquge.com.cn/book/14745/",
    "author": "唐川",
    "lastUpdate": 1556236800,
    "status": 1
}, {
    "tag": "修真小说",
    "tag_url": "https://www.biquge.com.cn/xiuzhen/",
    "source": "笔趣阁",
    "aid": 17785,
    "title": "家里养个狐狸精",
    "href": "https://www.biquge.com.cn/book/17785/",
    "author": "唐川",
    "lastUpdate": 1556236800,
    "status": 1
}, {
    "tag": "玄幻小说",
    "tag_url": "https://www.biquge.com.cn/xuanhuan/",
    "source": "笔趣阁",
    "aid": 9083,
    "title": "武道至尊",
    "href": "https://www.biquge.com.cn/book/9083/",
    "author": "暗夜幽殇",
    "lastUpdate": 1553731200,
    "status": 1
}, {
    "tag": "玄幻小说",
    "tag_url": "https://www.biquge.com.cn/xuanhuan/",
    "source": "笔趣阁",
    "aid": 10926,
    "title": "哥几个，走着",
    "href": "https://www.biquge.com.cn/book/10926/",
    "author": "纯银耳坠",
    "lastUpdate": 1552780800,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 8104,
    "title": "我们是兄弟",
    "href": "https://www.biquge.com.cn/book/8104/",
    "author": "纯银耳坠",
    "lastUpdate": 1552780800,
    "status": 1
}, {
    "tag": "玄幻小说",
    "tag_url": "https://www.biquge.com.cn/xuanhuan/",
    "source": "笔趣阁",
    "aid": 19775,
    "title": "狙猎神王",
    "href": "https://www.biquge.com.cn/book/19775/",
    "author": "盘丝小枣",
    "lastUpdate": 1546473600,
    "status": 1
}, {
    "tag": "修真小说",
    "tag_url": "https://www.biquge.com.cn/xiuzhen/",
    "source": "笔趣阁",
    "aid": 13406,
    "title": "纯阳战神",
    "href": "https://www.biquge.com.cn/book/13406/",
    "author": "燕灵君副号",
    "lastUpdate": 1539216000,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 14398,
    "title": "校花的贴身狂少",
    "href": "https://www.biquge.com.cn/book/14398/",
    "author": "独孤逝水",
    "lastUpdate": 1538870400,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 19074,
    "title": "官场布衣",
    "href": "https://www.biquge.com.cn/book/19074/",
    "author": "如水追梦",
    "lastUpdate": 1533859200,
    "status": 1
}, {
    "tag": "网游小说",
    "tag_url": "https://www.biquge.com.cn/wangyou/",
    "source": "笔趣阁",
    "aid": 18077,
    "title": "网游之诛神重生",
    "href": "https://www.biquge.com.cn/book/18077/",
    "author": "李小猫",
    "lastUpdate": 1533600000,
    "status": 1
}, {
    "tag": "历史小说",
    "tag_url": "https://www.biquge.com.cn/lishi/",
    "source": "笔趣阁",
    "aid": 18829,
    "title": "回到晚清的特种狙击手",
    "href": "https://www.biquge.com.cn/book/18829/",
    "author": "东一方",
    "lastUpdate": 1533513600,
    "status": 1
}, {
    "tag": "玄幻小说",
    "tag_url": "https://www.biquge.com.cn/xuanhuan/",
    "source": "笔趣阁",
    "aid": 10483,
    "title": "执掌乾坤",
    "href": "https://www.biquge.com.cn/book/10483/",
    "author": "乌山云雨",
    "lastUpdate": 1532563200,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 19001,
    "title": "超级保镖在都市",
    "href": "https://www.biquge.com.cn/book/19001/",
    "author": "萧忆情",
    "lastUpdate": 1532563200,
    "status": 1
}, {
    "tag": "玄幻小说",
    "tag_url": "https://www.biquge.com.cn/xuanhuan/",
    "source": "笔趣阁",
    "aid": 16703,
    "title": "武极碎空",
    "href": "https://www.biquge.com.cn/book/16703/",
    "author": "穆毅",
    "lastUpdate": 1532217600,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 19636,
    "title": "官道之步步高升",
    "href": "https://www.biquge.com.cn/book/19636/",
    "author": "北岸",
    "lastUpdate": 1527465600,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 9177,
    "title": "官道无疆",
    "href": "https://www.biquge.com.cn/book/9177/",
    "author": "瑞根",
    "lastUpdate": 1522454400,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 7741,
    "title": "重生之妖孽人生",
    "href": "https://www.biquge.com.cn/book/7741/",
    "author": "黄金战士",
    "lastUpdate": 1521849600,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 12051,
    "title": "超品透视",
    "href": "https://www.biquge.com.cn/book/12051/",
    "author": "李闲鱼",
    "lastUpdate": 1519344000,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 14624,
    "title": "重活之官路",
    "href": "https://www.biquge.com.cn/book/14624/",
    "author": "赵子铭",
    "lastUpdate": 1515974400,
    "status": 1
}, {
    "tag": "修真小说",
    "tag_url": "https://www.biquge.com.cn/xiuzhen/",
    "source": "笔趣阁",
    "aid": 7598,
    "title": "仙府之缘",
    "href": "https://www.biquge.com.cn/book/7598/",
    "author": "百里玺",
    "lastUpdate": 1514678400,
    "status": 1
}, {
    "tag": "历史小说",
    "tag_url": "https://www.biquge.com.cn/lishi/",
    "source": "笔趣阁",
    "aid": 8167,
    "title": "金鳞开",
    "href": "https://www.biquge.com.cn/book/8167/",
    "author": "美味罗宋汤",
    "lastUpdate": 1514678400,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 17315,
    "title": "最佳导演",
    "href": "https://www.biquge.com.cn/book/17315/",
    "author": "机器人瓦力",
    "lastUpdate": 1514678400,
    "status": 1
}, {
    "tag": "修真小说",
    "tag_url": "https://www.biquge.com.cn/xiuzhen/",
    "source": "笔趣阁",
    "aid": 19824,
    "title": "紫府仙缘",
    "href": "https://www.biquge.com.cn/book/19824/",
    "author": "百里玺",
    "lastUpdate": 1514678400,
    "status": 1
}, {
    "tag": "科幻小说",
    "tag_url": "https://www.biquge.com.cn/kehuan/",
    "source": "笔趣阁",
    "aid": 17313,
    "title": "末世超级商人",
    "href": "https://www.biquge.com.cn/book/17313/",
    "author": "雨水",
    "lastUpdate": 1514678400,
    "status": 1
}, {
    "tag": "历史小说",
    "tag_url": "https://www.biquge.com.cn/lishi/",
    "source": "笔趣阁",
    "aid": 21535,
    "title": "特种兵之利刃",
    "href": "https://www.biquge.com.cn/book/21535/",
    "author": "蝼蚁望天",
    "lastUpdate": 1514332800,
    "status": 1
}, {
    "tag": "玄幻小说",
    "tag_url": "https://www.biquge.com.cn/xuanhuan/",
    "source": "笔趣阁",
    "aid": 24772,
    "title": "九真九阳",
    "href": "https://www.biquge.com.cn/book/24772/",
    "author": "杜灿",
    "lastUpdate": 1514332800,
    "status": 1
}, {
    "tag": "修真小说",
    "tag_url": "https://www.biquge.com.cn/xiuzhen/",
    "source": "笔趣阁",
    "aid": 7564,
    "title": "百炼成仙",
    "href": "https://www.biquge.com.cn/book/7564/",
    "author": "幻雨",
    "lastUpdate": 1512950400,
    "status": 1
}, {
    "tag": "其他小说",
    "tag_url": "https://www.biquge.com.cn/qita/",
    "source": "笔趣阁",
    "aid": 13543,
    "title": "阴阳鬼医",
    "href": "https://www.biquge.com.cn/book/13543/",
    "author": "沙中灰",
    "lastUpdate": 1512000000,
    "status": 1
}, {
    "tag": "都市小说",
    "tag_url": "https://www.biquge.com.cn/dushi/",
    "source": "笔趣阁",
    "aid": 21616,
    "title": "绝色总裁爱上我",
    "href": "https://www.biquge.com.cn/book/21616/",
    "author": "风吹过的秋天",
    "lastUpdate": 1511740800,
    "status": 1
}]